# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: '<span style="font-size: 1.1rem;">People</span>'
    url: people
    weight: 20
  - name: '<span style="font-size: 1.1rem;">Events</span>'
    url: event
    weight: 30
  - name: '<span style="font-size: 1.1rem;">Blogs</span>'
    url: blog
    weight: 40
  - name: '<span style="font-size: 1.1rem;">Talks</span>'
    url: talk
    weight: 50
  - name: '<span style="font-size: 1.1rem;">News</span>'
    url: post
    weight: 60
  - name: '<span style="font-size: 1.1rem;">Get Involved</span>'
    url: membership
    weight: 70
  - name: '<span style="font-size: 1.1rem;">Publications</span>'
    url: publication
    weight: 80
  - name: '<span style="font-size: 1.1rem;">Contact</span>'
    url: contact
    weight: 90

  - name: "<i class='fab fa-github fa-2x'></i>"
    url: https://github.com/rse-asia/RSE_Asia
    weight: 100
  - name: "<i class='fas fa-envelope fa-2x'></i>"
    url: mailto:rse.asia.association@gmail.com
    weight: 101
  - name: "<i class='fab fa-linkedin fa-2x'></i>"
    url: https://www.linkedin.com/company/rse-asia-association/
    weight: 112
