# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: rse_asia
  theme_night: 
  font: native
  font_size: S

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo research group theme powered by Wowchemy website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice: '
      <section style="width: 100vw; margin-left: calc(-50vw + 50%); background-color: #343a40; padding: 8px 0;">
        <div style="max-width: 1200px; margin: 0 auto; padding: 0 20px; color: white; text-align: center;">
         <div style="display: flex; justify-content: center; gap:80px; text-align:left; margin-bottom: 20px;">
            <div>
              <strong>RSE Asia</strong><br>
              <a href="/" style="color:white;">Home</a><br>
              <a href="/people/" style="color:white;">People</a><br>
              <a href="/event/" style="color:white;">Events</a><br>
              <a href="/post/" style="color:white;">News</a><br>
              <a href="/contact/" style="color:white;">Contact</a>
            </div>

            <div>
              <strong>RSAA</strong><br>
              <a href="/rsaa/rsaa26/" style="color:white;">RSAA 2026</a><br>
              <a href="/rsaa/rsaa25/" style="color:white;">RSAA 2025</a><br>
              <a href="/rsaa/rseaa24/" style="color:white;">RSEAA 2024</a><br>
              <a href="/rsaa/rseaa23/" style="color:white;">RSEAA 2023</a><br>
              <a href="/rsaa/rseaa22/" style="color:white;">RSEAA 2022</a>
            </div>

            <div>
              <strong>Resources</strong><br>
              <a href="https://zenodo.org/communities/rse-asia-association/records?q=&l=list&p=1&s=10&sort=newest" style="color:white;">Resource Sheets</a><br>
              <a href="https://www.youtube.com/@RSEAsiaAssociation" style="color:white;">Recordings</a>
            </div>
 
         </div>
          © {year} Research Software Engineering Asia Association. This work is
          <a href="/license" style="color: white; text-decoration: underline;">licensed</a> under CC BY 4.0 International.
        </div>
      </section>'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false   

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-uk

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/rse-asia/RSE_Asia'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
