---
title: "The Quest for the Data Workbench"
description: |
  RSE Asia Community Call: Guest - Pieter van der Hijden.

url: https://rse-asia.github.io/RSE_Asia/
preview: 
date: 10-26-2023
base_url: https://rse-asia.github.io/RSE_Asia/
twitter:
  creator: "@RSE_Asia"
categories: [Research Software Engineering, Alt-text, Accessibility, Illustration]
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      out.width = "100%",
                      out.extra="style='border:1px solid black;'")
```

## Community call: Guest - Pieter van der Hijden

Pieter van der Hijden is an international management consultant specializing in "ICT for Sustainable Development Goals (SDGs)." His expertise lies in gaming and simulation, digital making (including fab labs and STEM learning), and e-learning (distance learning, Moodle). Pieter is based in Amsterdam, The Netherlands, and operates from his own consultancy, Sofos Consultancy. He has set up two fab labs in Suriname and does volunteer work in the global fab lab network, especially around Fablabs & SDGs.

During this Community Call, Pieter will share his insights on "The Quest for the Data Workbench: How to bridge the gap between the Sustainable Development Goals (SDGs) and the Fablab/Maker Movement?"

### More information

- Learn more about Pieter van der Hijden on his LinkedIn profile: [Pieter van der Hijden](https://www.linkedin.com/in/pietervdh/)

- Explore the Fab Foundation: [Fab Foundation](https://fabfoundation.org/)

When: Thursday, 26th October 2023, 8:00 AM - 9:00 AM UTC

Where: Online



